export const PUT_HITS = 'PUT_HITS';
export const HITS_LOAD = 'HITS_LOAD';
export const HITS_ERROR = 'HITS_ERROR';

export const PUT_CATEGORIES = 'PUT_CATEGORIES';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const DECLARE_LOADING_CATEGORIES = 'DECLARE_LOADING_CATEGORIES';

export const PUT_CATALOG_ITEMS = 'PUT_CATALOG_ITEMS';
export const PUT_MORE_ITEMS = 'PUT_MORE_ITEMS';
export const REPORT_COMPLETION_OF_ITEMS = 'REPORT_COMPLETION_OF_ITEMS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const DECLARE_LOADING_CATALOG = 'DECLARE_LOADING_CATALOG';
export const DECLARE_LOADING_MORE_PRODUCTS = 'DECLARE_LOADING_MORE_PRODUCTS';
export const CATALOG_ERROR = 'CATALOG_ERROR';

export const PUT_PRODUCT = 'PUT_PRODUCT';
export const DECLARE_LOADING_PRODUCT = 'DECLARE_LOADING_PRODUCT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_CART_OWNER = 'SET_CART_OWNER';
export const CLEAR_CART = 'CLEAR_CART';
export const SET_STATUS = 'SET_STATUS';
export const DECLARE_LOADING_ORDER = 'DECLARE_LOADING_ORDER';
